sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t iaurimas/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run iaurimas/react-test npm test -- --coverage

after_success:
  - docker build -t iaurimas/multi-client ./client
  - docker build -t iaurimas/multi-nginx ./nginx
  - docker build -t iaurimas/multi-server ./server
  - docker build -t iaurimas/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push iaurimas/multi-client
  - docker push iaurimas/multi-nginx
  - docker push iaurimas/multi-server
  - docker push iaurimas/multi-worker


deploy:
  provider: elastikbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "eu-north-1"
  app: "MultiDocker-env"
  env: "MultidockerEnv-env"

  #S3 bucket and initial app folder
  bucket_name: "elasticbeanstalk-eu-north-1-860177140429"
  bucket_path: "MultidockerEnv-env"
#Deploy code only when pushed to master
