language: generic
#Super user level permision to execute build
sudo: required
#we need a copy of docker ready to run
services:
  - docker


before_install:
  - docker build -t iaurimas/react-test -f ./client/Dockerfile.dev ./client


#https://facebook.github.io/create-react-app/docs/running-tests#linux-macos-bash
#https://docs.docker.com/engine/reference/run/#env-environment-variables
script:
  - docker run -e CI=true iaurimas/react-test npm run test
#build production images
after_success:
  - docker build -t iaurimas/multi-client ./client
  - docker build -t iaurimas/multi-nginx ./nginx
  - docker build -t iaurimas/multi-server ./server
  - docker build -t iaurimas/multi-worker ./worker
#Allow travis to Login to docker cli

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#Take those images and push to Dockerhub

  - docker push iaurimas/multi-client
  - docker push iaurimas/multi-nginx
  - docker push iaurimas/multi-server
  - docker push iaurimas/multi-worker


deploy:
  provider: elastikbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "eu-north-1"
  app: "multi-docker"
  env: "MultiDocker-env"

  #S3 bucket and initial app folder
  bucket_name: "elasticbeanstalk-eu-north-1-860177140429"
  bucket_path: "multi-docker"
#Deploy code only when pushed to master
