#Specify docker-compose version
version: '3'
#Creating containers
services:
  postgres:
    image: 'postgres:latest' #using latest postgress image
  redis:
    image: 'redis:latest' #using latest redis image from docker hub

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server #Use  directory to find dockerfile and build container from it
    depends_on:
    - postgres

    volumes:
      - /app/node_modules  # telling not to map node_modules
      - ./server:/app  # telling to map /server app directory on a Container to local working directory

#setting env variables from /server/keys
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgress
      - PGHOST=postgress
      - PGDATABASE=postgress
      - PGPASSWORD=postgress_password
      - PGPORT=5432
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
        - /app/node_modules  # telling not to map node_modules
        - ./client:/app


  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
          - /app/node_modules  # telling not to map node_modulesa
          - ./worker:/app
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379


  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
        - '3050:80'
